/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf,v 5.3 2002/12/05 00:29:45 hardaker Exp $
 */
#ifndef FLOWTAGTABLE_H
#define FLOWTAGTABLE_H

/* path to where netflow bdf files get dumped on meters */
#define NETFLOW_DIR "/var/log/netflow/ready"
/* #define NETFLOW_DIR "/tmp" */

#define MAX_ROWS 128	/* Max number of rows in snmp table. This is the same as the number of flowtags */
#define INTERVAL 900      /* The interval in seconds to refresh the table, normally 15min (than refresh at 0,15,30,45 every hour) */
#define OFFSET 60        /* Seconds offset from the interval time, normally 1-2min (than refresh is 3,18,33,48 minutes every hour if above is set to 15min)*/

/* function declarations */
void init_flowtagTable(void);
void initialize_table_flowtagTable(void);
Netsnmp_Node_Handler flowtagTable_handler;

Netsnmp_Node_Handler get_NetflowTimestamp;
Netsnmp_Node_Handler get_NetflowFlowCount;

/* column number definitions for table flowtagTable */
       #define COLUMN_FLOWTAGINDEX		1
       #define COLUMN_FLOWTAGDESCR		2
       #define COLUMN_FLOWTAGMBYTESFROM		3
       #define COLUMN_FLOWTAGMBYTESTO		4
       #define COLUMN_FLOWCOUNTBYTAG		5
#endif /* FLOWTAGTABLE_H */
